import React from 'react';
import { ArrowLeft, FileText, ChevronRight } from 'lucide-react';

interface TermsPageProps {
  onNavigate: (screen: 'landing' | 'login' | 'about' | 'dashboard') => void;
  isAuthenticated: boolean;
}

export default function TermsPage({ onNavigate, isAuthenticated }: TermsPageProps) {
  return (
    <div className="space-y-10 animate-fadeIn max-w-4xl mx-auto min-h-screen">
      {/* Visual Title Header */}
      <div className="bg-white rounded-[32px] p-8 md:p-12 shadow-sm border border-gray-100 space-y-6">
        <div className="flex items-center gap-3">
          <div className="w-12 h-12 rounded-2xl bg-rose-500/10 text-rose-500 flex items-center justify-center shrink-0">
            <FileText size={24} />
          </div>
          <div>
            <span className="px-2.5 py-0.5 rounded-full text-[9px] font-extrabold uppercase tracking-widest bg-rose-50 border border-rose-100 text-rose-500">
              OFFICIAL SERVICE LEGAL
            </span>
            <h1 className="text-2xl font-serif font-black text-[#0E1338] tracking-tight mt-1">
              Terms & Conditions of Service
            </h1>
          </div>
        </div>

        <p className="text-gray-400 text-xs italic">
          Last revised: May 23, 2026. {isAuthenticated ? 'Enterprise Merchant Policy' : 'Guest Mode Compliance Policy'}
        </p>

        <div className="border-t border-gray-100 pt-6 text-gray-655 text-xs md:text-sm space-y-6 leading-relaxed">
          {isAuthenticated ? (
            /* ================= MERCHANT ENTERPRISE COMPLIANCE (6 CLAUSES) ================= */
            <div className="space-y-6">
              <section className="space-y-2">
                <h2 className="font-bold text-[#0E1338] text-sm flex items-center gap-2">
                  <span className="text-[#00A6FF] font-black">1.</span> Master PIN Security Liabilities
                </h2>
                <p className="text-gray-500 text-xs md:text-sm">
                  Clerk workstation locks operate locally on secure browser state and cookies. It is the absolute, sole responsibility of the store's master owner to record and secure workstation master codes and PIN credentials. Yeedem Books cannot be held liable for delayed or locked workstation sessions stemming from forgotten access PINs.
                </p>
              </section>

              <section className="space-y-2">
                <h2 className="font-bold text-[#0E1338] text-sm flex items-center gap-2">
                  <span className="text-[#00A6FF] font-black">2.</span> Local Caching Fallbacks
                </h2>
                <p className="text-gray-500 text-xs md:text-sm">
                  An advanced unsynchronized local caching layer ensures resilient transaction logging even under extreme local network and cellular network fluctuations. Active local data caches are automatically synchronized with cloud persistent databases immediately upon connection recovery.
                </p>
              </section>

              <section className="space-y-2">
                <h2 className="font-bold text-[#0E1338] text-sm flex items-center gap-2">
                  <span className="text-[#00A6FF] font-black">3.</span> Trader Credit Aging Metrics
                </h2>
                <p className="text-gray-500 text-xs md:text-sm">
                  The system computes active debt balances based on transaction timestamps. Debt categorization and trader credit aging alerts are calculated in accordance with common 2026 Nigerian MSME bookkeeping best practices, assisting managers in mitigating credit liabilities.
                </p>
              </section>

              <section className="space-y-2">
                <h2 className="font-bold text-[#0E1338] text-sm flex items-center gap-2">
                  <span className="text-[#00A6FF] font-black">4.</span> Official FIRS-Mode Bookkeeping Advice
                </h2>
                <p className="text-gray-500 text-xs md:text-sm">
                  All printable receipts and bookkeeping templates generated by the workbench are formatted to support small businesses aligning with standard Federal Inland Revenue Service (FIRS) 2026 bookkeeping templates. However, Yeedem Books is a supportive tool, and its use does not replace professional legal, financial, or tax audit assessments.
                </p>
              </section>

              <section className="space-y-2">
                <h2 className="font-bold text-[#0E1338] text-sm flex items-center gap-2">
                  <span className="text-[#00A6FF] font-black">5.</span> Data Ownership and Portability
                </h2>
                <p className="text-gray-500 text-xs md:text-sm">
                  Registered merchants retain full proprietary ownership of customer records, item parameters, historical trade logs, and active debtor listings. You have complete rights to export, clear, or purge your local business profile data safely at any moment.
                </p>
              </section>

              <section className="space-y-2">
                <h2 className="font-bold text-[#0E1338] text-sm flex items-center gap-2">
                  <span className="text-[#00A6FF] font-black">6.</span> Audit Trail Accountability
                </h2>
                <p className="text-gray-500 text-xs md:text-sm">
                  Active cashier sessions and daily journal adjustments are logged securely within browser storage lines to ensure strict compliance, preventing arbitrary data tampering by guest clerks or third-party attendants.
                </p>
              </section>
            </div>
          ) : (
            /* ================= GUEST TRIAL COMPLIANCE ================= */
            <div className="space-y-6">
              <section className="space-y-2">
                <h2 className="font-bold text-[#0E1338] text-sm flex items-center gap-2">
                  <span className="text-[#00A6FF] font-black">1.</span> Guest Trial Allocations & Access Limits
                </h2>
                <p className="text-gray-500 text-xs md:text-sm">
                  Yeedem Books provides a lightweight, unauthenticated service ("Guest Mode"). Guest Mode allows prospective merchants to compile and download up to 2 trial invoices without establishing credentials. These records are saved briefly within local browser memory and are subject to hardware fingerprint allocations.
                </p>
              </section>

              <section className="space-y-2">
                <h2 className="font-bold text-[#0E1338] text-sm flex items-center gap-2">
                  <span className="text-[#00A6FF] font-black">2.</span> Physical Device Storage Constraints
                </h2>
                <p className="text-gray-500 text-xs md:text-sm">
                  All guest invoices and compiled data reside solely in memory and local cookie storage. Closing private browsing tabs, switching workstations, or deleting browser history will immediately clear Guest-state parameters and cannot be restored by the platform.
                </p>
              </section>
            </div>
          )}
        </div>
      </div>

      {/* Static banner element at the end of text */}
      <div className="flex flex-col sm:flex-row items-center justify-between gap-4 max-w-xl mx-auto pt-4 pb-8 bg-gray-50/50 rounded-2xl p-4 border border-gray-100">
        <button
          onClick={() => onNavigate('landing')}
          className="px-4 py-2 text-xs font-bold text-gray-500 hover:text-[#0E1338] flex items-center gap-1.5 hover:underline transition font-sans"
        >
          <ArrowLeft size={14} /> See Marketplace
        </button>

        {!isAuthenticated && (
          <button
            onClick={() => onNavigate('login')}
            className="px-5 py-2.5 bg-[#00A6FF] hover:bg-opacity-95 text-white text-xs font-bold rounded-xl flex items-center gap-1.5 transition shadow-sm"
          >
            Sign In / Register <ChevronRight size={14} />
          </button>
        )}
      </div>
    </div>
  );
}
