# Generated by Django 5.0.14 on 2026-05-29 13:13

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessProfile",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.models.generate_biz_id,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "business_name",
                    models.CharField(default="My SME Business", max_length=255),
                ),
                (
                    "business_type",
                    models.CharField(
                        choices=[
                            ("buy_and_sell", "Buy and Sell"),
                            ("service", "Service"),
                        ],
                        default="buy_and_sell",
                        max_length=50,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "invoice_template_preference",
                    models.CharField(default="classic", max_length=50),
                ),
                ("owner_pin", models.CharField(blank=True, max_length=10, null=True)),
                ("shop_slug", models.CharField(blank=True, max_length=255, null=True)),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                ("is_suspicious_locked", models.BooleanField(default=False)),
                (
                    "business_logo",
                    models.TextField(
                        blank=True,
                        help_text="Base64 representation or logo image URL",
                        null=True,
                    ),
                ),
                (
                    "custom_accent_color",
                    models.CharField(default="#00A6FF", max_length=50),
                ),
                ("custom_font_size", models.CharField(default="md", max_length=20)),
                ("custom_font_family", models.CharField(default="sans", max_length=30)),
                ("custom_show_logo", models.BooleanField(default=True)),
                (
                    "custom_header_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("custom_footer_notes", models.TextField(blank=True, null=True)),
                ("custom_shadow_style", models.CharField(default="sm", max_length=30)),
                ("logo_width", models.IntegerField(default=80)),
                ("logo_height", models.IntegerField(default=80)),
                ("logo_rotation", models.IntegerField(default=0)),
                ("header_rotation", models.IntegerField(default=0)),
                (
                    "header_styles_json",
                    models.JSONField(
                        blank=True,
                        help_text="JSON mapping for header fonts and colors",
                        null=True,
                    ),
                ),
                (
                    "customer_styles_json",
                    models.JSONField(
                        blank=True,
                        help_text="JSON mapping for customer section styles",
                        null=True,
                    ),
                ),
                (
                    "table_styles_json",
                    models.JSONField(
                        blank=True,
                        help_text="JSON mapping for table display text",
                        null=True,
                    ),
                ),
                (
                    "footer_styles_json",
                    models.JSONField(
                        blank=True,
                        help_text="JSON mapping for bottom details",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.models.generate_cust_id,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "active_debt_balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customers",
                        to="api.businessprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.models.generate_inv_id,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "customerName",
                    models.CharField(
                        help_text="Flat name mapping of client", max_length=255
                    ),
                ),
                (
                    "productName",
                    models.CharField(
                        help_text="Flat product list snapshot descriptor",
                        max_length=255,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "amount_paid",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "debt_balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("sale", "Sale Transaction"),
                            ("expense", "Expense Ledger"),
                            ("payment_on_account", "Advance Payment"),
                        ],
                        default="sale",
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft Phase"),
                            ("PAID", "Settled & Paid"),
                            ("OVERDUE", "Aged Balance Overdue"),
                        ],
                        default="OVERDUE",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="api.businessprofile",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="api.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.models.generate_item_id,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("quantity", models.IntegerField(default=1)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="api.invoice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LedgerBackup",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.models.generate_bkp_id,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("backup_data", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledgers_backups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MerchantSession",
            fields=[
                (
                    "session_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "device_fingerprint",
                    models.CharField(default="unknown_fp", max_length=255),
                ),
                (
                    "last_active_ip",
                    models.CharField(default="127.0.0.1", max_length=100),
                ),
                (
                    "last_active_region",
                    models.CharField(default="NG-Lagos", max_length=100),
                ),
                ("is_suspicious_locked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merchant_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.models.generate_prod_id,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("sku", models.CharField(blank=True, max_length=100, null=True)),
                ("stock", models.IntegerField(default=0)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "cost_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("min_quantity_count", models.IntegerField(default=5)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="api.businessprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LowStockNotification",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.models.generate_notif_id,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="warnings",
                        to="api.businessprofile",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="api.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.models.generate_staff_id,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name_slug", models.CharField(max_length=100)),
                ("real_name", models.CharField(max_length=255)),
                ("owner_generated_pin", models.CharField(max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("shop_id", models.CharField(default="default_shop", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffActivityLog",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.models.generate_log_id,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action_taken", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("is_flagged", models.BooleanField(default=False)),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="api.staff",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="SupplierRecord",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.models.generate_supp_id,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("supplier_name", models.CharField(max_length=255)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "outstanding_balance_owed",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suppliers",
                        to="api.businessprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InventoryIntakeLog",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=api.models.generate_restock_id,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("amount", models.IntegerField(default=0)),
                (
                    "unit_cost_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="restocks",
                        to="api.product",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_inputs",
                        to="api.supplierrecord",
                    ),
                ),
            ],
        ),
    ]
